# Use Apify's Python base image
FROM apify/actor-python:3.12

# Copy requirements and install Python dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the source code
COPY . ./

# Run the API
CMD ["python", "app/api.py"]
